export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const INCREMENT_ITEM_IN_CART = "INCREMENT_ITEM_IN_CART";
export const DECREMENT_ITEM_IN_CART = "DECREMENT_ITEM_IN_CART";
